### ISSUE TITLE
VLC QT interface and uninstallation screwy

### ISSUE THREAD

**Issue by ghost** [negativo17/vlc#1]
**Version:**  4.749293f.fc24

Everything is oversized to the point of being unusable. Whenever I play a video, it's tiny and appears in the corner of the screen. The screenshot looks overblown, but I have not scaled or edited it in any way. My DPI settings have not changed, VLC is the only thing affected. If I try to downgrade, it tries to install the RPMFusion version which results in conflicts.
- Videos are normal if I launch them via another interface, i.e `cvlc`.
- Changing settings, resetting preferences, deleting `.cache`, `.config`, etc. doesn't fix things. Neither does manually running `vlc-cache-gen`
- `dnf remove vlc` doesn't actually seem to remove anything as all of the files persist. 

Please click on the screenshot to see the fullsize version, the distortion is what I see when running the application.

![vlc interface](https://cloud.githubusercontent.com/assets/20711066/18227886/928d15dc-7202-11e6-95ca-a4c0376e55c0.png)

![playing video](https://cloud.githubusercontent.com/assets/20711066/18227891/ee23abc2-7202-11e6-8dbd-0b6daa5adf0f.png)

**Comment by scaronni** [comment]
That's weird, never seen it. Can you tell me which combination of drivers and video acceleration you are using?

**Comment by ghost** [comment]
367.44 `nvidia-driver` from your repository. The entire application has oversized icons/text, hardware acceleration or not. The preferences are default, so output and hardware-accelerated decoding is automatic, etc.

**Comment by ghost** [comment]
Seems like I figured out the problem. The commit causing this issue is:

https://github.com/videolan/vlc/commit/a4b9ccf1007827a364e1dc44a462187bab960459

```
+#if HAS_QT56
+    QApplication::setAttribute( Qt::AA_EnableHighDpiScaling );
+#endif
+
```

I compiled against that commit, removed the line and everything is normal now. Luckily VLC is extremely modular so recompiling it took zero time at all.

**Comment by scaronni** [comment]
Same setup here but did not happen, I guess it's because I don't have any HiDPI screen.

I'm about to push an update with a recent tarball, I've not found anything in the commit logs that revert and/or update this change, so I guess that in case of a new package you will get the same issue.

**Comment by ghost** [comment]
The issue goes away if I set the environment variable `QT_AUTO_SCREEN_SCALE_FACTOR` to false. So nothing further needs to be done on your part. However, it's pretty ridiculous that I had to consult the Qt documentation to solve the issue. VLC should at least make the setting optional.

I'm fairly certain that I don't have a HiDpi monitor. The issue may result from the combination of manually enabling the HiDpi setting with this [commit](https://github.com/videolan/vlc/commit/c290464a2f9a2974d3f107f6316227b18cdbd490) which changes DPI calculations. I'll do some further investigation with a different monitor and the commits later.
