### ISSUE TITLE
vlc fails to find drivers

### ISSUE THREAD

**Issue by dfche** [negativo17/vlc#11]
When I try to run vlc (dvd files on hard drive) I get the following

vlc
VLC media player 3.0.17.4 Vetinari (revision )
[00005616491f6bc0] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0000561649298d20] main playlist: playlist is empty
[00007fe9c4011ef0] dvdnav demux error: Couldn't find device name.
[00007fe9c4011ef0] dvdnav demux error: Can't read name block. Probably not a DVD-ROM device.
[00007fe9c4011ef0] dvdnav demux: DVD disk reports itself with Region mask 0x00c00000. Regions: 01 02 03 04 05 06
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007fe9b8001b40] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[00007fe9b8001b40] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
[00007fe9b8001b40] glconv_vaapi_drm gl error: vaInitialize: unknown libva error
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_10
Segmentation fault (core dumped)

Drivers (i965_drv_video.so, nvidia_driv_video.so) are present:

ls -al /usr/lib64/dri
total 354980
drwxr-xr-x.   2 root root     4096 Dec 23 11:58 .
dr-xr-xr-x. 229 root root   225280 May  2 12:29 ..
-rwxr-xr-x.   5 root root 16271736 Oct 11  2021 i915_dri.so
-rwxr-xr-x.   5 root root 16271736 Oct 11  2021 i965_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 iris_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 kms_swrast_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 nouveau_dri.so
-rwxr-xr-x.   3 root root 11999640 Oct 11  2021 nouveau_drv_video.so
-rwxr-xr-x.   5 root root 16271736 Oct 11  2021 nouveau_vieux_dri.so
lrwxrwxrwx.   1 root root       18 Jan 27  2021 nvidia_drv_video.so -> vdpau_drv_video.so
-rwxr-xr-x.   5 root root 16271736 Oct 11  2021 r200_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 r300_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 r600_dri.so
-rwxr-xr-x.   3 root root 11999640 Oct 11  2021 r600_drv_video.so
-rwxr-xr-x.   5 root root 16271736 Oct 11  2021 radeon_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 radeonsi_dri.so
-rwxr-xr-x.   3 root root 11999640 Oct 11  2021 radeonsi_drv_video.so
lrwxrwxrwx.   1 root root       18 Jan 27  2021 s3g_drv_video.so -> vdpau_drv_video.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 swrast_dri.so
-rwxr-xr-x.   1 root root    90704 Jan 27  2021 vdpau_drv_video.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 virtio_gpu_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 vmwgfx_dri.so
-rwxr-xr-x.  10 root root 24579352 Oct 11  2021 zink_dri.so

rpm -qi vlc
Name        : vlc
Epoch       : 1
Version     : 3.0.17.4
Release     : 1.fc34
Architecture: x86_64
Install Date: Wed 13 Apr 2022 01:11:05 PM EDT
Group       : Unspecified
Size        : 58687963
License     : GPLv2+
Signature   : DSA/SHA1, Mon 11 Apr 2022 02:38:46 AM EDT, Key ID 14386362f90c0e97
Source RPM  : vlc-3.0.17.4-1.fc34.src.rpm
Build Date  : Mon 11 Apr 2022 01:53:51 AM EDT
Build Host  : workstation.localdomain
URL         : http://www.videolan.org
Summary     : The cross-platform open-source multimedia framework, player and server
Description :
VLC is a free and open source cross-platform multimedia player and framework
that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various
streaming protocols.

I haven't used vlc a lot so I am not sure exactly when this condition arose. I am using multimedia repository.

**Comment by scaronni** [comment]
Sorry, Fedora 34 is EOL.

**Comment by dfche** [comment]
The problem persists on FC 35. I attach my case at end. 

Discussion of related(?) issues is at

https://github.com/intel/libva-utils/issues/154
[scaronni.txt](https://github.com/negativo17/vlc/files/8901807/scaronni.txt)

**Comment by dfche** [comment]
On Tue, 2022-06-14 at 05:11 -0700, Simone Caronni wrote:
> Closed #11 as completed.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

I added information that the problem persists in Fedora 35.

**Comment by scaronni** [comment]
Can you paste the output of this command?
```
$ rpm -qa intel-media-driver intel-vaapi-driver
```

**Comment by scaronni** [comment]
Why are you disabling `nouveau`? Is it an Optimus laptop? Do you have the Nvidia drivers installed? The `scaronni.txt` file mentions only the Intel card.

**Comment by dfche** [comment]
On Mon, 2022-06-20 at 02:26 -0700, Simone Caronni wrote:
> Why are you disabling nouveau? Is it an Optimus laptop? Do you have
> the Nvidia drivers installed? The scaronni.txt file mentions only the
> Intel card.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

It's dual boot with Fedora and Windows.

I disabled nouveau to use fedora -- this was admittedly several
years ago when I first tried to use as an optimus laptop and more
or less gave up. I vaguely recall that the laptop did not boot 
and/or was so unstable that was the only solution.

I installed the negativo17 multimedia tools. I thought both nvidia and
intel tools were present.

Here is the current configuration

Dell Inc. XPS 15 9560
Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8
NVIDIA GeForce GTX 1050/PCIe/SSE2 / Mesa Intel® HD Graphics 630 (KBL
GT2)
Gnome 41.6 Wayland

rpm -qa | grep -i nvid

nvidia-kmod-common-515.48.07-2.fc35.noarch
akmod-nvidia-515.48.07-1.fc35.x86_64
nvidia-driver-libs-515.48.07-1.fc35.x86_64
nvidia-driver-515.48.07-1.fc35.x86_64
nvidia-driver-cuda-libs-515.48.07-1.fc35.x86_64
kmod-nvidia-5.17.12-200.fc35.x86_64-515.48.07-1.fc35.x86_64
kmod-nvidia-5.17.8-200.fc35.x86_64-515.48.07-1.fc35.x86_64
kmod-nvidia-5.17.13-200.fc35.x86_64-515.48.07-1.fc35.x86_64

lspci -v
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core
Processor Host Bridge/DRAM Registers (rev 05)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0
	Capabilities: <access denied>
	Kernel driver in use: skl_uncore

00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe
Controller (x16) (rev 05) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 122
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	I/O behind bridge: 0000e000-0000efff [size=4K]
	Memory behind bridge: ec000000-ed0fffff [size=17M]
	Prefetchable memory behind bridge: 00000000c0000000-
00000000d1ffffff [size=288M]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630
(rev 04) (prog-if 00 [VGA controller])
	DeviceName:  Onboard IGD
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0, IRQ 139
	Memory at eb000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 80000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200
v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 05)
	Subsystem: Dell Device 07be
	Flags: fast devsel, IRQ 16
	Memory at ed120000 (64-bit, non-prefetchable) [size=32K]
	Capabilities: <access denied>
	Kernel driver in use: proc_thermal
	Kernel modules: processor_thermal_device_pci_legacy

00:14.0 USB controller: Intel Corporation 100 Series/C230 Series
Chipset Family USB 3.0 xHCI Controller (rev 31) (prog-if 30 [XHCI])
	Subsystem: Dell Device 07be
	Flags: bus master, medium devsel, latency 0, IRQ 131
	Memory at ed110000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: xhci_hcd

00:14.2 Signal processing controller: Intel Corporation 100 Series/C230
Series Chipset Family Thermal Subsystem (rev 31)
	Subsystem: Dell Device 07be
	Flags: fast devsel, IRQ 18
	Memory at ed138000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel_pch_thermal
	Kernel modules: intel_pch_thermal

00:15.0 Signal processing controller: Intel Corporation 100 Series/C230
Series Chipset Family Serial IO I2C Controller #0 (rev 31)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at ed137000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss

00:15.1 Signal processing controller: Intel Corporation 100 Series/C230
Series Chipset Family Serial IO I2C Controller #1 (rev 31)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0, IRQ 17
	Memory at ed136000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: intel-lpss

00:16.0 Communication controller: Intel Corporation 100 Series/C230
Series Chipset Family MEI Controller #1 (rev 31)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0, IRQ 129
	Memory at ed135000 (64-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: mei_me
	Kernel modules: mei_me

00:17.0 SATA controller: Intel Corporation HM170/QM170 Chipset SATA
Controller [AHCI Mode] (rev 31) (prog-if 01 [AHCI 1.0])
	Subsystem: Dell Device 07be
	Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 128
	Memory at ed130000 (32-bit, non-prefetchable) [size=8K]
	Memory at ed134000 (32-bit, non-prefetchable) [size=256]
	I/O ports at f090 [size=8]
	I/O ports at f080 [size=4]
	I/O ports at f060 [size=32]
	Memory at ed133000 (32-bit, non-prefetchable) [size=2K]
	Capabilities: <access denied>
	Kernel driver in use: ahci

00:1c.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset
Family PCI Express Root Port #1 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 123
	Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
	I/O behind bridge: [disabled]
	Memory behind bridge: ed200000-ed3fffff [size=2M]
	Prefetchable memory behind bridge: [disabled]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1c.1 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset
Family PCI Express Root Port #2 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 124
	Bus: primary=00, secondary=03, subordinate=03, sec-latency=0
	I/O behind bridge: 0000d000-0000dfff [size=4K]
	Memory behind bridge: ed400000-eddfffff [size=10M]
	Prefetchable memory behind bridge: 00000000d2100000-
00000000d2afffff [size=10M]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1d.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset
Family PCI Express Root Port #9 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 125
	Bus: primary=00, secondary=04, subordinate=04, sec-latency=0
	I/O behind bridge: [disabled]
	Memory behind bridge: ede00000-edefffff [size=1M]
	Prefetchable memory behind bridge: [disabled]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1d.4 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset
Family PCI Express Root Port #13 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 126
	Bus: primary=00, secondary=05, subordinate=05, sec-latency=0
	I/O behind bridge: [disabled]
	Memory behind bridge: [disabled]
	Prefetchable memory behind bridge: [disabled]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1d.6 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset
Family PCI Express Root Port #15 (rev f1) (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 127
	Bus: primary=00, secondary=06, subordinate=3e, sec-latency=0
	I/O behind bridge: 00002000-00002fff [size=4K]
	Memory behind bridge: d4000000-ea0fffff [size=353M]
	Prefetchable memory behind bridge: 0000000090000000-
00000000b1ffffff [size=544M]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:1f.0 ISA bridge: Intel Corporation HM175 Chipset LPC/eSPI Controller
(rev 31)
	Subsystem: Dell Device 07be
	Flags: bus master, medium devsel, latency 0

00:1f.2 Memory controller: Intel Corporation 100 Series/C230 Series
Chipset Family Power Management Controller (rev 31)
	Subsystem: Dell Device 07be
	Flags: fast devsel
	Memory at ed12c000 (32-bit, non-prefetchable) [disabled]
[size=16K]

00:1f.3 Audio device: Intel Corporation CM238 HD Audio Controller (rev
31) (prog-if 80)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 32, IRQ 141
	Memory at ed128000 (64-bit, non-prefetchable) [size=16K]
	Memory at ed100000 (64-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

00:1f.4 SMBus: Intel Corporation 100 Series/C230 Series Chipset Family
SMBus (rev 31)
	Subsystem: Dell Device 07be
	Flags: medium devsel, IRQ 16
	Memory at ed132000 (64-bit, non-prefetchable) [size=256]
	I/O ports at f040 [size=32]
	Kernel driver in use: i801_smbus
	Kernel modules: i2c_i801

01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050
Mobile] (rev a1)
	Subsystem: Dell Device 07be
	Flags: bus master, fast devsel, latency 0, IRQ 143
	Memory at ec000000 (32-bit, non-prefetchable) [size=16M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	Memory at d0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	Expansion ROM at ed000000 [virtual] [disabled] [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia

02:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless
Network Adapter (rev 32)
	Subsystem: Rivet Networks Killer Wireless-n/a/ac 1535 Wireless
Network Adapter
	Flags: bus master, fast devsel, latency 0, IRQ 142
	Memory at ed200000 (64-bit, non-prefetchable) [size=2M]
	Capabilities: <access denied>
	Kernel driver in use: ath10k_pci
	Kernel modules: ath10k_pci

03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd.
RTS525A PCI Express Card Reader (rev 01)
	Subsystem: Dell Device 07be
	Physical Slot: 1
	Flags: bus master, fast devsel, latency 0, IRQ 130
	Memory at ed400000 (32-bit, non-prefetchable) [size=4K]
	Capabilities: <access denied>
	Kernel driver in use: rtsx_pci
	Kernel modules: rtsx_pci

04:00.0 Non-Volatile memory controller: Toshiba Corporation XG4 NVMe
SSD Controller (rev 01) (prog-if 02 [NVM Express])
	Subsystem: Toshiba Corporation Device 0001
	Flags: bus master, fast devsel, latency 0, IRQ 16, NUMA node 0
	Memory at ede00000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: nvme
	Kernel modules: nvme

**Comment by dfche** [comment]
On Mon, 2022-06-20 at 02:24 -0700, Simone Caronni wrote:
> Can you paste the output of these commands?
> $ rpm -qa intel-media-driver intel-vaapi-driver
> $ lspci | grep -i vga
> $ vainfo
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

***@***.*** ~]$ rpm -qa intel-media-driver intel-vaapi-driver
***@***.*** ~]$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630
(rev 04)
***@***.*** ~]$ vainfo
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
***@***.*** ~]$

**Comment by scaronni** [comment]
You're missing the drivers, that's why none is found.
So please install the VA-API driver for Intel  and Nvidia:
```
yum -y install intel-media-driver intel-vaapi-driver nvidia-vaapi-driver
```
If you use Steam In-Home Streaming also install the 32 bit Intel drivers:
```
yum -y install intel-media-driver.i686 intel-vaapi-driver.i686
```

**Comment by dfche** [comment]
Thanks! I was able to install intel-media-driver intel-vaapi-driver
but not nvidia-vaapi-driver (many conflicts). This seems to solve
the vlc problem in any case. 

Here are the issues with nvidia-vaapi-driver

sudo dnf install nvidia-vaapi-driver
Last metadata expiration check: 2:21:32 ago on Tue 21 Jun 2022 06:08:17
AM EDT.
Error: 
 Problem: package nvidia-vaapi-driver-0.0.5-3.fc35.i686 requires
libgstcodecparsers-1.0.so.0, but none of the providers can be installed
  - package gstreamer1-plugins-bad-1:1.20.0-1.fc35.x86_64 obsoletes
gstreamer1-plugins-bad-free < 1:1.20.0-1.fc35 provided by gstreamer1-
plugins-bad-free-1.19.2-1.fc35.1.i686
  - package gstreamer1-plugins-bad-1:1.20.0-1.fc35.x86_64 obsoletes
gstreamer1-plugins-bad-free < 1:1.20.0-1.fc35 provided by gstreamer1-
plugins-bad-free-1.20.0-1.fc35.i686
  - problem with installed package gstreamer1-plugins-bad-1:1.20.0-
1.fc35.x86_64
  - installed package gstreamer1-plugins-bad-1:1.20.0-1.fc35.x86_64
obsoletes gstreamer1-plugins-bad-free < 1:1.20.0-1.fc35 provided by
gstreamer1-plugins-bad-free-1.19.2-1.fc35.1.i686
  - installed package gstreamer1-plugins-bad-1:1.20.0-1.fc35.x86_64
obsoletes gstreamer1-plugins-bad-free < 1:1.20.0-1.fc35 provided by
gstreamer1-plugins-bad-free-1.20.0-1.fc35.i686
  - conflicting requests
  - problem with installed package libva-vdpau-driver-0.7.4-
110.fc35.x86_64
  - package nvidia-vaapi-driver-0.0.6-1.fc35.x86_64 conflicts with
libva-vdpau-driver(x86-64) provided by libva-vdpau-driver-0.7.4-
110.fc35.x86_64

and on my system

rpm -qi libva-vdpau-driver-0.7.4-110.fc35.x86_64
Name        : libva-vdpau-driver
Version     : 0.7.4
Release     : 110.fc35
Architecture: x86_64
Install Date: Mon 23 May 2022 02:45:02 PM EDT
Group       : Unspecified
Size        : 115467
License     : GPLv2+
Signature   : RSA/SHA256, Mon 26 Jul 2021 12:27:52 AM EDT, Key ID
db4639719867c58f
Source RPM  : libva-vdpau-driver-0.7.4-110.fc35.src.rpm
Build Date  : Thu 22 Jul 2021 12:18:42 PM EDT
Build Host  : buildvm-x86-27.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://cgit.freedesktop.org/vaapi/vdpau-driver
Bug URL     : https://bugz.fedoraproject.org/libva-vdpau-driver
Summary     : HW video decode support for VDPAU platforms
Description :
VDPAU Backend for Video Acceleration (VA) API.

**Comment by scaronni** [comment]
Remove libva-vdpau-driver, it's obsolete.
