### ISSUE TITLE
Missing vlc-devel package after 20b35a9

### ISSUE THREAD

**Issue by pstrejajo** [negativo17/vlc#12]
Despite vlc package now provides vlc-devel package, there are no development files contained in vlc rpm itself.

**Comment by scaronni** [comment]
Thanks for reporting, this was some typo when adjusting the provides for the recently introduced VLC package in Fedora: https://github.com/negativo17/vlc/commit/a8cc4d6fed920be45656efe8a4988050d5b9d525

New package should be online soon.

May I ask what use do you have for the VLC headers?

**Comment by pstrejajo** [comment]
Thank you for quick update. I have made some kaffeine patches, just for my liking. Some OSD related, switching channels with mouse wheel, or some new function to be used with a remote control. Nothing really fancy, but lack of this "features" just bugged me. Probably rebuilding kaffeine every Fedora version update is not necessary, but I don't  want to have some  "old" packages, at least if I have control over them.
