### ISSUE TITLE
VLC dependency for DVD menu and audio possibly broken

### ISSUE THREAD

**Issue by tbelvin** [negativo17/vlc#2]
VLC 3.0.0.16 has lost DVD menu playback and cannot play all DVD audio tracks on updates-testing

Using 'dnf downgrade --allowerasing vlc ffmpeg-devel' and then rebuilding VLC source rpm 3.0.0.0.9 on updates-testing with ffmpeg 3.1.7.1 works

I tried reporting at RPM Fusion first and got this response:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=4456

**Comment by scaronni** [comment]
You got the correct answer, this is not an RPMFusion package. You should open bugs to RPMFusion for packages hosted by the project, not for mine.

Will look into it.

**Comment by scaronni** [comment]
It does not start automatically on DVD menus, but if you use the "normal" layout of the DVD, it works. For normal I mean with the disclaimers and what not before the menu. To make a test:

Tools -> Preferences -> Show settings: ALL
Input codecs -> Access modules -> DVD with menus
Untick the option "Start directly in menu".
Save the preferences then exit and restart VLC.
