### ISSUE TITLE
fedora 25 build dependencies

### ISSUE THREAD

**Issue by hdfssk** [negativo17/vlc#3]
I'm trying to rebuild your vlc package locally (on fedora 25), but am hitting problems fulfilling the 100 pkgconfig build dependencies. Lines like this…

    BuildRequires:  pkgconfig(avahi-client) >= 0.6

…don’t make it clear what package needs to be installed, and obvious guesses don't necessarily work:

    $ sudo dnf install avahi-client-devel
    Last metadata expiration check: 0:31:40 ago on Fri Jun 23 16:08:33 2017.
    No package avahi-client available.
    No package avahi-client-devel available.
    Error: Unable to find a match.

What packages need to be installed to build your vlc rpm?

**Comment by scaronni** [comment]
So...

1) That's the proper way to specify dependencies if the build system is asking for pkg-config files:

https://fedoraproject.org/wiki/Packaging:Guidelines#BuildRequires_based_on_pkg-config

I think you should familiarize a bit yourself with packaging in Fedora:
```
$ sudo dnf provides "pkgconfig(avahi-client)"
Last metadata expiration check: 1:53:54 ago on Fri Jun 23 21:18:00 2017.
avahi-devel-0.6.32-4.fc25.i686 : Libraries and header files for avahi development
Repo        : fedora

avahi-devel-0.6.32-4.fc25.x86_64 : Libraries and header files for avahi development
Repo        : fedora
```
2) Just let dnf install the package for you, don't you think?

`$ sudo dnf builddep vlc.spec`

Do you think people would just read a list and install packages by hand one by one for thousands of packages that make up a distribution?

3) Can you tell me why are you rebuilding it? What is missing? What does not work?
I can probably add it to the build in the repository.

**Comment by scaronni** [comment]
I forgot, there's also 4:

4) Familiarize yourself with mock, and you will not need any devel package installed on your system to compile stuff. Mock is also used in the official Koji buildservers:

`mock -v --rebuild -r fedora-25-x86_64 /path/to/some/source.src.rpm`

**Comment by scaronni** [comment]
https://fedoraproject.org/wiki/Packaging:PkgConfigBuildRequires

**Comment by hdfssk** [comment]
Thanks Simone, this is good info that got vlc built… yep, I’d been manually installing build dependencies, so `dnf install depends` and mock will definitely improve rpm working conditions.

I’m rebuilding to run the attached _don’t auto-resize vlc to taller than the screen height_ patch. When I was starting a 720p video on a 720p screen, the vlc window’s controls appeared below the screen bottom. Details below, patch/spec file are in [maxwindowsize.zip](https://github.com/negativo17/vlc/files/1100018/maxwindowsize.zip).

It’d be great to get this into the repo build, I’m glad to make a pull request or for your changes (eg. attached spec uses release 19.gitstuff.1 — 20.gitstuff?) Let me know what I can do, and thanks again.

> Make vlc take the interface’s height into account while resizing when a new video’s loaded. Currently, when ‘Interface > Main interfaces > Qt > Resize interface to the native video size’ is turned on and ‘Video > Window properties > Video width & height’ are set to adaptive/-1 only the video’s size is checked, so playing a 720p vid on a 720p monitor resizes vlc to be taller than the screen.
> Before: ![before](https://user-images.githubusercontent.com/8379226/27512090-c14fa158-5903-11e7-8e5b-e7b55b5cf52b.jpeg)
> After: ![after](https://user-images.githubusercontent.com/8379226/27512098-e480fa14-5903-11e7-9c5a-bcbbb8b4be2a.jpeg)

**Comment by scaronni** [comment]
Thanks for the explanation. I'm quite surprised, my settings are exactly like described above, and if I open a video file bigger than my screen resolution the window is still fullscreen but is scaled to accomodate the video on the whole screen, and the toolbar is there.

At least on my system it seems not needed. Do you know why upstream is not accepting it?

**Comment by hdfssk** [comment]
Your experience makes sense, I only hit this problem opening a video file the _same_ size as the screen. Upstream currently downscales larger-than-screen videos, but its idea of what's larger than the screen is just based on the video’s picture size — ignoring the extra height added by the interface. Opening a 720p video when plugged into a 720p TV should hit it; videos slightly smaller than the screen would too.

Upstream does calculate the interface’s height _after_ asking “is this video larger than the screen?”, so this patch now does that same calculation _before_ asking; it uses that info to adjust the video’s width & height a new way. However, if you look closely at the “After” pic above, you’ll notice that adjustment isn’t perfect (note the small black bars in the window above & below the vid itself), so I decided to field test the patch for a few days and see if it seems worth troubleshooting further before making the upstream pull request. So, while I expect the patch will ultimately be accepted, it hasn’t been submitted yet… no worries if you’d rather wait on upstream than add this as a patch.

**Comment by scaronni** [comment]
Well, I'm updating the VLC package. If you don't mind, once you send the pull request please link it here and I will include it.

Thanks!
