### ISSUE TITLE
/var/tmp/rpm-tmp.tWrA0o: line 6: /usr/bin/ldconfig: No such file or directory                                                                                                      

### ISSUE THREAD

**Issue by barsnick** [negativo17/vlc#5]
The SPEC file for vlc apparently codes ldconfig in the `%post` section as `%{_bindir}/ldconfig`. This leads to the quoted error:
```  Running scriptlet: vlc-1:3.0.1-1.fc27.x86_64                                                                                                                               77/144
  Cleanup          : vlc-1:3.0.1-1.fc27.x86_64                                                                                                                               77/144
  Running scriptlet: vlc-1:3.0.1-1.fc27.x86_64                                                                                                                               77/144
/var/tmp/rpm-tmp.tWrA0o: line 6: /usr/bin/ldconfig: No such file or directory
```

The problem is that ldconfig on current Fedora is in `%{_sbindir}`. F26 and upwards should have macros for this, provided in redhat-rpm-config, as macros.ldconfig:
https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/master/f/macros.ldconfig

So use of `%ldconfig_post` or at least `%{ldconfig}` would be advised, unless the SPEC aims to be more generic.

**Comment by scaronni** [comment]
Fixed it in the epel-7 branch and forgot to do it in the Fedora branch.

Thanks.

https://github.com/negativo17/vlc/commit/f70e020ac9890f75f26338e26e4d7476cc69e77c
